FROM ubuntu:latest

RUN apt-get update && apt-get install -y cron

# Add cronjob file in the cron directory
RUN echo "*/1 * * * * root cp -r /data1/* /data/ \\n" >> /etc/crontab

CMD ["cron", "-f"]





